-- MySQL Script generated by MySQL Workbench
-- Sun 25 Jun 2017 02:59:18 PM BRT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema torcrawler
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema torcrawler
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `torcrawler` DEFAULT CHARACTER SET utf8 ;
USE `torcrawler` ;

-- -----------------------------------------------------
-- Table `torcrawler`.`HiddenServices`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `torcrawler`.`HiddenServices` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(2048) NULL,
  `Url` VARCHAR(2048) NOT NULL,
  `Status` INT NOT NULL,
  `FirstScan` DATETIME NULL,
  `LatestScan` DATETIME NULL,
  `LastSeenOnline` DATETIME NULL,
  `ResponsibleThread` BIGINT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `torcrawler`.`Links`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `torcrawler`.`Links` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Url` VARCHAR(2048) NOT NULL,
  `Title` VARCHAR(2048) NULL,
  `CreatedOn` DATETIME NOT NULL,
  `HiddenServiceId` INT NULL,
  `ResourcePath` VARCHAR(2048) NULL,
  `IsIndex` TINYINT(1) NULL,
  `HTMLHash` VARCHAR(32) NULL,
  `Status` SMALLINT NOT NULL,
  `Header` VARCHAR(4096) NULL,
  PRIMARY KEY (`Id`),
  INDEX `HiddenService_Link_FK_idx` (`HiddenServiceId` ASC),
  CONSTRAINT `HiddenService_Link_FK`
    FOREIGN KEY (`HiddenServiceId`)
    REFERENCES `torcrawler`.`HiddenServices` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `torcrawler`.`Report`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `torcrawler`.`Report` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `StartTime` DATETIME NULL,
  `FinishTime` DATETIME NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `torcrawler`.`DataGroup`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `torcrawler`.`DataGroup` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `ReportId` INT NULL,
  `Label` VARCHAR(128) NULL,
  PRIMARY KEY (`Id`),
  INDEX `DataGroup_Report_FK_idx` (`ReportId` ASC),
  CONSTRAINT `DataGroup_Report_FK`
    FOREIGN KEY (`ReportId`)
    REFERENCES `torcrawler`.`Report` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `torcrawler`.`Data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `torcrawler`.`Data` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Label` VARCHAR(128) NULL,
  `Data` VARCHAR(128) NULL,
  `DataGroupId` INT NULL,
  PRIMARY KEY (`Id`),
  INDEX `Data_DataGroup_FK_idx` (`DataGroupId` ASC),
  CONSTRAINT `Data_DataGroup_FK`
    FOREIGN KEY (`DataGroupId`)
    REFERENCES `torcrawler`.`DataGroup` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
